#!/bin/bash

# Git TLS SSL disable
export GIT_SSL_NO_VERIFY="true" 

# colors
export TERM='xterm-256color'
export CLICOLOR=1

# Mastercard certs
source "$WILLIAM_DEV/tools/macbook-setup/mc-laptop-env.sh"

# AWS DevVM aliases
. "$WILLIAM_DOTFILES/tools/vagrant_aliases"

# MacPorts 
export PATH="$PATH:/opt/local/bin:/opt/local/sbin"

# CARGO
export CARGO_HOME="$WILLIAM_DOTFILES/tools/cargo"
export PATH="$CARGO_HOME/bin:$PATH"

# Go setup
export PATH="$PATH:/usr/local/go/bin"

# Newer gradle
export PATH="/opt/gradle/gradle-7.3.3/bin:$PATH"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# AWS-CLI
export PATH="/opt/aws-cli:$PATH"

# Vagrant
export PATH="/opt/vagrant/bin:$PATH"

# FZF
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

