#!/bin/bash

# colors
export TERM='xterm-256color'
export CLICOLOR=1

# MacPorts 
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"

# CARGO
. "$HOME/.cargo/env"

# Newer gradle
export PATH="/opt/gradle/gradle-7.3.3/bin:$PATH"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

